[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"

[env]
ESP_LOG = "trace"

[build]
rustflags = ["-C", "force-frame-pointers"]

target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["core"]
